/**
 * Maps UI routes to help documentation slugs.
 * Slugs correspond to files in /docs/help/{slug}.md (and /public/help/{slug}.md).
 */
export const helpMapping: Record<string, string> = {
  '/agent-view': 'agent-view',
  '/': 'getting-started',
  '/project/[slug]': 'project-details',
  '/manual-steps': 'manual-steps',
  '/stats': 'stats',
  '/sessions': 'sessions',
  '/sessions/[sessionId]': 'sessions',
  '/insights': 'insights',
  '/board': 'board',
  '/agents': 'agents',
  '/skills': 'skills',
  '/instructions': 'instructions',
  '/usage': 'usage',
  '/costs': 'cost-report',
  '/status': 'status',
  '/templates': 'templates',
  '/templates/[slug]': 'templates',
  '/config': 'config',
  '/setup': 'setup',
  '/settings': 'settings',
  '/settings/scan-roots': 'settings',
  '/settings/cost': 'cost',
  '/settings/notifications': 'notifications',
  '/settings/integrations': 'telegram',
  '/settings/terminal': 'terminal',
  '/settings/auto-title': 'auto-title',
  '/settings/live-activity': 'live-activity',
  '/settings/adapters': 'adapters',
  '/adapters': 'adapters',
  '/kanban': 'kanban',
  '/tasks': 'tasks',
  '/schedule': 'tasks',
  '/plans': 'plans',
  '/hooks': 'hooks',
  '/plugins': 'plugins',
  '/sql': 'sql',
  '/library': 'library',
  '/new-project': 'new-project',
  '/insights-report': 'insights-report',
  '/memory': 'memory',
  '/memory/seed': 'memory',
  '/memory/triage': 'memory',
  '/background': 'background',
  '/commands': 'commands',
  '/projects': 'projects',
  '/swarms': 'swarms',
}

/**
 * Maps detail-page tab values to contextual help slugs.
 * Used by ProjectDetail to open the right doc when ? is clicked on a tab.
 */
export const tabHelpMapping: Record<string, string> = {
  overview: 'project-details',
  context: 'claude-md-audit',
  todos: 'project-details',
  sessions: 'sessions',
  costs: 'cost-report',
  'manual-steps': 'manual-steps',
  insights: 'insights',
  board: 'board',
  ops: 'operations',
  agents: 'agents',
  skills: 'skills',
  memory: 'memory',
  planning: 'gsd-planning',
  efficiency: 'project-details',
  'hot-files': 'project-details',
  patterns: 'project-details',
  handoff: 'sessions',
  orchestration: 'sessions',
  'config-history': 'config-history',
  mcp: 'mcp-security',
}

/** All available help doc slugs. */
export const helpSlugs = [
  'getting-started',
  'search-and-filter',
  'project-details',
  'dev-servers',
  'ports',
  'project-status',
  'tech-stack',
  'quick-actions',
  'manual-steps',
  'stats',
  'sessions',
  'insights',
  'board',
  'operations',
  'agents',
  'skills',
  'instructions',
  'usage',
  'cost-report',
  'status',
  'memory',
  'claude-md-audit',
  'config',
  'config-history',
  'setup',
  'settings',
  'demo-mode',
  'service-mode',
  'tray-app',
  'templates',
  'plans',
  'hooks',
  'plugins',
  'sql',
  'notifications',
  'telegram',
  'terminal',
  'auto-title',
  'otel',
  'cost',
  'tasks',
  'kanban',
  'adapters',
  'mcp-security',
  'library',
  'new-project',
  'insights-report',
  'command-palette',
  'keyboard-shortcuts',
  'mcp-server',
  'mcp-health',
  'burn-hud',
  'workflow-launcher',
  'github-activity',
  'background',
  'commands',
  'projects',
  'swarms',
] as const

export type HelpSlug = (typeof helpSlugs)[number]
