import { NextResponse } from "next/server";
import { existsSync, statSync, readFileSync } from "fs";
import { homedir } from "os";
import { join, resolve } from "path";
import sanitizeHtml from "sanitize-html";

const REPORT_DIR = join(homedir(), ".claude", "usage-data");
const REPORT_FILE = join(REPORT_DIR, "report.html");

// Allowlist-based sanitization: keeps safe structural/presentational HTML,
// strips scripts, event handlers, and any tag not on the allowlist.
function sanitize(html: string): string {
  return sanitizeHtml(html, {
    allowedTags: sanitizeHtml.defaults.allowedTags.concat([
      "html", "head", "body", "title", "style",
      "main", "article", "section", "header", "footer", "nav",
      "figure", "figcaption", "details", "summary",
      "img", "picture", "source",
    ]),
    allowedAttributes: {
      ...sanitizeHtml.defaults.allowedAttributes,
      "*": ["class", "id", "style", "aria-*", "data-*", "role", "tabindex", "title", "lang", "dir"],
      a: ["href", "target", "rel", "class", "id"],
      img: ["src", "alt", "width", "height", "loading", "class"],
      td: ["colspan", "rowspan", "class"],
      th: ["colspan", "rowspan", "scope", "class"],
      col: ["span"],
      colgroup: ["span"],
    },
    allowedSchemes: ["http", "https", "mailto"],
    // Keep <style> block contents so the report renders correctly.
    // sanitize-html warns that <style> can be used for CSS injection; that risk
    // is acceptable here because the iframe uses bare sandbox="" (no scripts,
    // no same-origin access), and the report is locally generated by Claude Code.
    allowVulnerableTags: true,
    allowedStyles: { "*": {} },
  });
}

export async function GET() {
  // Containment check: ensure the resolved path stays within the expected dir
  const resolved = resolve(REPORT_FILE);
  if (!resolved.startsWith(resolve(REPORT_DIR))) {
    return NextResponse.json({ error: "Path traversal rejected" }, { status: 400 });
  }

  if (!existsSync(resolved)) {
    return NextResponse.json({
      exists: false,
      mtime: null,
      sizeBytes: null,
      html: null,
    });
  }

  const stat = statSync(resolved);
  const raw = readFileSync(resolved, "utf-8");
  const html = sanitize(raw);

  return NextResponse.json({
    exists: true,
    mtime: stat.mtime.toISOString(),
    sizeBytes: stat.size,
    html,
  });
}
