/** Sentinel embedded in the User-Agent header so we can reliably identify
 *  and remove Project Minder-managed hook entries from ~/.claude/settings.json. */
export const SENTINEL_UA = "project-minder-live-activity/1";

/**
 * Distinct sentinel for the BLOCKING approval hook.
 *
 * Two reasons it is not the same string as `SENTINEL_UA`:
 *
 * 1. **Idempotent upgrade.** `installLiveActivityHooks` skips an event that
 *    already has a managed entry. A user who installed hooks before this
 *    feature existed already has a managed `PreToolUse` entry, so a shared
 *    sentinel would make the installer skip the event and never add the
 *    blocking command — the gate would stay unreachable forever.
 * 2. **Origin check.** `/api/hooks` 403s anything that is not the
 *    live-activity sentinel; the approval route wants to recognise its own
 *    caller separately, since the two receivers have very different
 *    consequences.
 *
 * `isManagedCommand` matches BOTH, so uninstall still removes everything
 * Minder wrote without needing to know which kind it is.
 */
export const SENTINEL_UA_APPROVAL = "project-minder-approval-gate/1";

/**
 * Build the curl command Claude Code will run for each registered lifecycle
 * hook event. The command reads the JSON payload from stdin and POSTs it to
 * the hook receiver.
 *
 * Uses double-quoted strings so the command works on both Windows (cmd.exe /
 * PowerShell) and Unix (bash/sh). The sentinel User-Agent is used server-side
 * to verify the request origin, and by the remove helper to identify our entries.
 */
export function buildCurlCommand(hookUrl: string): string {
  return (
    `curl -sS -X POST "${hookUrl}"` +
    ` -H "Content-Type: application/json"` +
    ` -A "${SENTINEL_UA}"` +
    ` --data-binary @-`
  );
}

/** Returns true if the command string was generated by Project Minder —
 *  either receiver. Used by uninstall, so it must match every kind. */
export function isManagedCommand(command: string): boolean {
  return command.includes(SENTINEL_UA) || command.includes(SENTINEL_UA_APPROVAL);
}

/** Returns true for the blocking approval command specifically. */
export function isApprovalCommand(command: string): boolean {
  return command.includes(SENTINEL_UA_APPROVAL);
}

/**
 * Derive the approval receiver's URL from the configured lifecycle hook URL.
 *
 * The installer is handed one URL (`…/api/hooks`) and both receivers live
 * under it, so deriving beats asking the caller for a second URL that could
 * drift to a different host or port. Any query string or fragment on the
 * input is dropped: they are meaningless here and would end up on the wrong
 * side of the appended path segment.
 */
export function deriveApprovalUrl(hookUrl: string): string {
  try {
    const u = new URL(hookUrl);
    u.search = "";
    u.hash = "";
    u.pathname = u.pathname.replace(/\/+$/, "") + "/permission";
    return u.toString();
  } catch {
    // Not a parseable URL — the install route validates before we get here,
    // so this is only reachable from direct calls. Fall back to naive
    // concatenation rather than throwing during hook installation.
    return hookUrl.replace(/\/+$/, "") + "/permission";
  }
}

/**
 * Build the curl command for the BLOCKING approval hook (`PreToolUse`).
 *
 * Differs from `buildCurlCommand` in two ways that carry the whole
 * fail-open guarantee:
 *
 * 1. **`--max-time`** — curl itself enforces a ceiling, so the tool call
 *    cannot hang even if the server accepts the connection and then never
 *    answers (process suspended, machine slept, deadlock). Set a couple of
 *    seconds above the server's own deadline so the server normally wins
 *    the race and can return a considered `ask`; curl's timeout is the
 *    backstop, not the primary path.
 *
 * 2. **`-f` (`--fail`)** — on any HTTP error, curl writes NOTHING to
 *    stdout and exits non-zero. Combined with `-sS` (errors to stderr
 *    only), that means every failure produces empty stdout, which Claude
 *    Code treats as "the hook expressed no opinion" and falls back to the
 *    normal permission prompt. The absence of output is therefore a safe
 *    default rather than a parse error.
 *
 * Note the ordering guarantee this relies on: stdout carries ONLY the
 * decision JSON. Anything else printed here (progress meters, error text)
 * would be fed to Claude Code's parser, which is why `-sS` is not
 * optional.
 */
export function buildApprovalCurlCommand(
  hookUrl: string,
  serverTimeoutMs: number
): string {
  // +3s over the server deadline: enough for connection setup and the
  // response to come back before curl gives up on a healthy server.
  const maxTimeSec = Math.max(1, Math.ceil(serverTimeoutMs / 1000) + 3);
  return (
    `curl -sS -f -X POST "${hookUrl}"` +
    ` -H "Content-Type: application/json"` +
    ` -A "${SENTINEL_UA_APPROVAL}"` +
    ` --max-time ${maxTimeSec}` +
    ` --data-binary @-`
  );
}
