/** Sentinel embedded in the User-Agent header so we can reliably identify
 *  and remove Project Minder-managed hook entries from ~/.claude/settings.json. */
export const SENTINEL_UA = "project-minder-live-activity/1";

/**
 * Build the curl command Claude Code will run for each registered lifecycle
 * hook event. The command reads the JSON payload from stdin and POSTs it to
 * the hook receiver.
 *
 * Uses double-quoted strings so the command works on both Windows (cmd.exe /
 * PowerShell) and Unix (bash/sh). The sentinel User-Agent is used server-side
 * to verify the request origin, and by the remove helper to identify our entries.
 */
export function buildCurlCommand(hookUrl: string): string {
  return (
    `curl -sS -X POST "${hookUrl}"` +
    ` -H "Content-Type: application/json"` +
    ` -A "${SENTINEL_UA}"` +
    ` --data-binary @-`
  );
}

/** Returns true if the command string was generated by Project Minder. */
export function isManagedCommand(command: string): boolean {
  return command.includes(SENTINEL_UA);
}
