"use client";

import { useEffect, useState } from "react";
import { formatRelativeTime } from "@/lib/utils";

interface ReportData {
  exists: boolean;
  mtime: string | null;
  sizeBytes: number | null;
  html: string | null;
}

export function InsightsReportViewer() {
  const [data, setData] = useState<ReportData | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch("/api/insights-report")
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((d: ReportData) => setData(d))
      .catch((e: unknown) => setError(e instanceof Error ? e.message : String(e)));
  }, []);

  if (error) {
    return (
      <div style={{ padding: "24px", color: "var(--error, #f87171)", fontSize: "0.82rem" }}>
        Failed to load report: {error}
      </div>
    );
  }

  if (!data) {
    return (
      <div style={{ padding: "24px", color: "var(--text-muted)", fontSize: "0.82rem" }}>
        Loading…
      </div>
    );
  }

  if (!data.exists || !data.html) {
    return (
      <div style={{ padding: "32px", maxWidth: "540px", margin: "0 auto" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: 600, color: "var(--text-primary)", marginBottom: "12px" }}>
          No insights report found
        </h2>
        <p style={{ fontSize: "0.82rem", color: "var(--text-secondary)", lineHeight: 1.6, marginBottom: "16px" }}>
          The report is generated by Claude Code. Run the following command in any terminal session,
          then reload this page:
        </p>
        <code style={{
          display: "block",
          padding: "10px 14px",
          borderRadius: "var(--radius)",
          border: "1px solid var(--border-subtle)",
          background: "var(--bg-surface)",
          fontFamily: "var(--font-mono)",
          fontSize: "0.82rem",
          color: "var(--text-primary)",
          userSelect: "all",
        }}>
          claude /insights
        </code>
        <p style={{ marginTop: "12px", fontSize: "0.75rem", color: "var(--text-muted)" }}>
          Expected location: <code style={{ fontFamily: "var(--font-mono)" }}>~/.claude/usage-data/report.html</code>
        </p>
      </div>
    );
  }

  const mtimeLabel = data.mtime
    ? `Generated ${formatRelativeTime(data.mtime)} · ${(data.sizeBytes! / 1024).toFixed(0)} KB`
    : null;

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "calc(100vh - 120px)" }}>
      {mtimeLabel && (
        <div style={{
          padding: "8px 16px",
          fontSize: "0.72rem",
          color: "var(--text-muted)",
          fontFamily: "var(--font-mono)",
          borderBottom: "1px solid var(--border-subtle)",
          background: "var(--bg-surface)",
          flexShrink: 0,
        }}>
          {mtimeLabel}
        </div>
      )}
      <iframe
        srcDoc={data.html}
        sandbox=""
        title="Claude Code Insights Report"
        style={{
          flex: 1,
          border: "none",
          width: "100%",
          background: "#fff",
        }}
      />
    </div>
  );
}
