/**
 * Deciding which transcript turns a *person* actually authored.
 *
 * A billing report is only as good as this predicate. Every false positive
 * opens a phantom attended block — potentially crediting an unattended
 * overnight agent run as supervised work — so the failure direction that
 * matters is counting machine turns as human, and the rules below are biased
 * accordingly.
 *
 * **Two layers, and the structural one does the heavy lifting.**
 *
 * 1. `sessions.entrypoint` (applied by the caller, not here): `sdk-*` means a
 *    program drove the session, so no turn in it is human. See
 *    `isAutomatedEntrypoint` in `../usage/entrypoint.ts`. This is the primary
 *    defence and it is worth more than every rule in this file — a full-corpus
 *    audit on 2026-08-09 found 7,493 plain-text user turns portfolio-wide, of
 *    which ~63 % were scripted agent invocations concentrated in a single
 *    cron-driven project (3,052 `"You are the staff historian for ..."`,
 *    422 session-summarizer prompts, 417 travel-writer prompts, 44 memory
 *    consolidation prompts). Filtering on `entrypoint` removes all of them
 *    without a single string match.
 *
 * 2. Text shape (this file): even inside a genuinely interactive session, the
 *    `user` role carries machine-injected turns. Those are the tagged blocks
 *    and the templated continuations enumerated below.
 *
 * **Why the `user` role alone is useless here.** In Claude Code JSONL, tool
 * results come back as `user` turns. On the sales-dashboards corpus that is
 * 6,821 of the 7,659 user turns (89 %). The caller strips those via
 * `tool_result_preview IS NOT NULL` before anything reaches this function.
 */

/**
 * Turns whose text is a machine-generated block wrapped in a marker tag.
 * Matched as prefixes on the trimmed preview.
 *
 * `<bash-input>` and `<command-name>` are deliberately **absent** — those are
 * a person typing `!ls` or `/pr-resolve`, which is exactly the supervised
 * activity being measured. On sales-dashboards they are 126 of 652 human
 * events (19 %); dropping them would under-bill by roughly a fifth.
 */
const MACHINE_TAG_PREFIXES = [
  "<bash-stdout>",
  "<bash-stderr>",
  "<local-command-stdout>",
  "<local-command-stderr>",
  "<task-notification>",
  "<system-reminder>",
  "<user-prompt-submit-hook>",
] as const;

/**
 * Untagged, templated turns that arrive as ordinary prose. Each pattern was
 * derived from a frequency scan of repeated openings across the whole corpus
 * rather than imagined, and the counts are portfolio-wide as of 2026-08-09.
 */
const SYNTHETIC_PROSE = [
  /** 208x — the post-compaction resume preamble. */
  /^This session is being continued from a previous conversation/i,
  /** The `!cmd` caveat block Claude Code injects before local command output. */
  /^Caveat: The messages below were generated by the user while running local commands/i,
  /** 290x — inter-agent messages in multi-session work. Not a person typing. */
  /^Another Claude session sent a message:/i,
  /** 185x + 109x — `/compact`, both its bare form and its expanded instruction. */
  /^Apply maximum non-destructive compression/i,
  /^\/compact\b/i,
  /**
   * Scripted agent invocations that leak into interactive sessions (a human
   * pasting a harness prompt is rare; a script emitting one is not). Kept
   * narrow — anchored, and requires an agent-ish role noun — so an ordinary
   * instruction like "you are right, revert it" is not swallowed.
   */
  /^You are summarizing a Claude Code session/i,
  /^You are (?:the|a|an) [^.\n]{0,60}?(?:agent|historian|writer|summarizer|reviewer bot)\b/i,
] as const;

/**
 * Was this `user`-role turn authored by a person?
 *
 * @param textPreview `turns.text_preview` — the first ~500 chars. Truncation
 *   is fine: every rule anchors at the start of the string.
 *
 * Callers must already have excluded tool-result turns, sidechain turns, and
 * automated-entrypoint sessions; this function judges text shape only.
 */
export function isHumanPrompt(textPreview: string | null | undefined): boolean {
  if (!textPreview) return false;
  const s = textPreview.trimStart();
  // Empty previews are meta/system turns that carry their payload elsewhere;
  // they are never a person typing.
  if (s === "") return false;
  if (MACHINE_TAG_PREFIXES.some((p) => s.startsWith(p))) return false;
  if (SYNTHETIC_PROSE.some((re) => re.test(s))) return false;
  return true;
}

/**
 * Interrupts (`[Request interrupted by user]`) are proof a human was present —
 * they physically pressed escape — but they are not a *prompt*. They are
 * counted as human presence so an interrupt keeps a block alive, while not
 * inflating the prompt count the report shows as its audit trail.
 */
export function isHumanInterrupt(textPreview: string | null | undefined): boolean {
  return !!textPreview && /^\[Request interrupted by user/i.test(textPreview.trimStart());
}
